name: jscatter

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - nodejs==16.6.*
  - matplotlib
  - numpy
  - pandas
  - pyarrow
  - pip
  - pip:
    - jupyterlab>=3.0.6
    - ipywidgets>=7.6.3
    - jupyterlab_widgets>=1.0.0
