name: jupyter-scatterplot

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.7
  - nodejs>=12.*
  - matplotlib
  - numpy
  - pip
  - pip:
    - jupyterlab>=1.1.1
    - ipywidgets>=7.5.1
