name: jscatter-py310-ipyw8-jlab3

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.10.*
  - numpy
  - pandas
  - pip
  - pip:
    - jupyterlab==3.*
    - ipywidgets==8.*
    - jupyterlab_widgets==3.*
    - jupyter-scatter
