name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: sudo apt-get install xvfb
      - run: npm ci
        working-directory: js
      - run: npm run build --if-present
        working-directory: js
        env:
          CI: true

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
        working-directory: js
      - run: npm run prerelease
        working-directory: js
      - run: npm publish
        working-directory: js
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
