import math

from ..font import arial

ASINH_1 = math.asinh(1)
INITIAL_TILE = '0,0,0'
MAX_ZOOM_LEVEL = 24
NUM_LABELS_SOLVE_ZOOM_LEVELS_APPROXIMATELY = 1000
NUM_LABELS_SOLVE_ZOOM_LEVELS_PRECISELY = 50
ZOOM_IN_PX = 100

DEFAULT_FONT_FACE = arial.regular
DEFAULT_FONT_SIZE = 16
DEFAULT_ZOOM_RANGE = (-math.inf, math.inf)
DEFAULT_TILE_SIZE = 256
DEFAULT_CHUNK_SIZE = 10000
DEFAULT_MAX_LABELS_PER_TILE = 100
